// Export pages
export 'inicio/inicio_widget.dart' show InicioWidget;
export 'registrar/registrar_widget.dart' show RegistrarWidget;
export 'articulos/articulos_widget.dart' show ArticulosWidget;
export 'empledos/empledos_widget.dart' show EmpledosWidget;
export 'venta/venta_widget.dart' show VentaWidget;
export 'almacen/almacen_widget.dart' show AlmacenWidget;
export 'carrito/carrito_widget.dart' show CarritoWidget;
export 'arroz/arroz_widget.dart' show ArrozWidget;
export 'frijoles/frijoles_widget.dart' show FrijolesWidget;
export 'elote/elote_widget.dart' show EloteWidget;
export 'cereal/cereal_widget.dart' show CerealWidget;
export 'atun/atun_widget.dart' show AtunWidget;
export 'sandia/sandia_widget.dart' show SandiaWidget;
export 'platano/platano_widget.dart' show PlatanoWidget;
export 'pina/pina_widget.dart' show PinaWidget;
export 'naranja/naranja_widget.dart' show NaranjaWidget;
export 'inicio2/inicio2_widget.dart' show Inicio2Widget;
export 'creditos/creditos_widget.dart' show CreditosWidget;
